danielhrisca/asammdf

- asammdf/mdf4.py
Hi Daniel,
With this fix, your module can now read every channel, even the ones who are in composition channel.
It uses a recursive function to walk and find every channel.
Cheers, Julien
> fix(mdf4): read channels of composition channel

- pylint.cfg
- setup.cfg
Add Jed's pylint config and setup config
> Integrate Jed's master branch changes

- asammdf/mdf4.py
> fix(mdf4): error maximum recursion exceeded

- MANIFEST.in
Changing the line in setup.py didn't work
> Exclude test folder in installation

- MANIFEST.in
Reverts danielhrisca/asammdf#47
> Revert "Exclude test folder in installation"

- asammdf/blocks/mdf_v4.py
> [Bugfix] do not edit groups if no processed can

- asammdf/blocks/mdf_v4.py
Do not process CAN database if db is None
> [Bugfix] attribute error when CAN database could not be loaded

- asammdf/blocks/v4_blocks.py
Hi Daniel,
I had a bunch of measurement with wrong XML syntax in head block comment so I had to implement this fix.
> fix parse error issue for header comment

- asammdf/blocks/mdf_v3.py
- asammdf/blocks/mdf_v4.py
- asammdf/signal.py
> Fixed all found occurrences of 'timstamps'

- asammdf/blocks/mdf_v4.py
Hi @danielhrisca 
I thought you might like to use next here instead of a for-loop
> use next() instead of a for-loop in mdf_v4._process_can_logging

- asammdf/gui/plot.py
- asammdf/signal.py
> Patch to avoid error when your enviroment doesn't have pyQT installed

- asammdf/mdf.py
Corrected typo in documentation.
> Typo correction.

- asammdf/blocks/bus_logging_utils.py
- asammdf/blocks/conversion_utils.py
- asammdf/blocks/mdf_common.py
- asammdf/blocks/mdf_v3.py
- asammdf/blocks/mdf_v4.py
- asammdf/blocks/utils.py
- asammdf/gui/dialogs/define_channel.py
- asammdf/gui/widgets/batch.py
- asammdf/gui/widgets/cursor.py
- asammdf/gui/widgets/dict_to_tree.py
- asammdf/gui/widgets/mdi_area.py
- asammdf/gui/widgets/plot.py
- asammdf/gui/widgets/tabular.py
- asammdf/mdf.py
- test/test_mdf.py
Merging this PR will help seeing only the essential changes of PR #446
> Cleaning before next release

- asammdf/blocks/mdf_v4.py
- asammdf/blocks/utils.py
- asammdf/mdf.py
- setup.py
> Fix #450 and improve canmatrix API usage

- asammdf/blocks/mdf_common.py
- asammdf/blocks/mdf_v3.py
- asammdf/blocks/mdf_v4.py
- asammdf/blocks/utils.py
- asammdf/mdf.py
This typo error was bothering me lately :)
> Fix typo for occurrence

- asammdf/blocks/mdf_common.py
- asammdf/mdf.py
I made this following a discussion I had today with gitMesa. See #493
> add acq_name argument to whereis

- asammdf/blocks/mdf_common.py
- asammdf/blocks/mdf_v3.py
- asammdf/blocks/mdf_v4.py
Hi @danielhrisca 
If I am correct, MDF_Common is an abstract class so I propose this refactoring for _filter_occurrences which better follows this design pattern
> Follow the abstract class design pattern

- asammdf/blocks/cutils.c
This includes a few issues found in the extract() function:
1. Align types with the Python interface (signed vs unsigned)
2. Calculate the size of the buffer coherently (sign issue again)
3. Avoid pointer arithmetic
> Fix segmentation violation when cutting files

- asammdf/gui/asammdfgui.py
- asammdf/gui/widgets/plot.py
- setup.py
See [here](https://github.com/pyqtgraph/pyqtgraph/pull/1509)
> Fix DPI issues

- asammdf/gui/dialogs/advanced_search.py
- asammdf/gui/dialogs/multi_search.py
- asammdf/gui/widgets/bar.py
- asammdf/gui/widgets/mdi_area.py
- asammdf/gui/widgets/numeric.py
new PR against development branch
> Use Pattern.search instead of match for search patterns

- asammdf/gui/widgets/file.py
> missing XML comment extraction and style

- asammdf/mdf.py
Concerning Issue #663 
Tested with the files I have (mdf 4.1).
> Reordering Channel Groups when concatenating

- asammdf/mdf.py
Continuing PR #664 
Apparently I messed up that PR, which was a surprise to me. (Sorry for the mess)
In any case, I found that an improvement is needed as some groups can have a similar name, path, etc. but different channel names. 
As such I've also added a test for names of channels.
Should work better now. 
I tested it by concatenating a few few files which have a certain counter, and plotting this counter, which seems to work fine value wise. 
There are issues with the new plotting system, but that is for another PR or issue.
> Reordering Channel Groups when concatenating v2

- asammdf/mdf.py
#712 
empty list was created because those channels weren't loaded.
Continue loop and perform action only to the group of channels that was loaded
+
Black formatting
> Issue #712

- asammdf/mdf.py
Test were failing because incorrect if in concatenation stopped the first file from closing. 
Tests passed on my pc, lets see if they pass on here as well.
> Incorrect if. first_mdf wasn't closed

- asammdf/mdf.py
- doc/conf.py
Sorry, I had an older version of black installed leading to wrong formatting that fails the github action style tests.
> Black formatting

- asammdf/blocks/mdf_v3.py
- asammdf/blocks/mdf_v4.py
Ticket #698 
To be honest this fix works but it's not that nice.
> Start time setters

- asammdf/blocks/mdf_v4.py
@danielhrisca could you do a release for this fix? Thanks!
> fix: :bug: CN block within CA block is not implemented yet

- asammdf/gui/widgets/main.py
> Fixed Typo 

- asammdf/mdf.py
- test/test_mdf.py
> fix for #776 -- case-sensitive matching in MDF.search(mode='wildcard', case_insensitive=True)

- src/asammdf/gui/widgets/tabular_base.py
> Fix AttributeError in HeaderNamesView

- setup.py
- src/asammdf/gui/asammdfgui.py
- src/asammdf/gui/dialogs/advanced_search.py
- src/asammdf/gui/dialogs/dependencies_dlg.py
- src/asammdf/gui/utils.py
- src/asammdf/gui/widgets/main.py
Feel free to close without merging, if you don't see any use for this 😄 
Unrelated, but included here:
The AppUserModelID helps the Windows taskbar to associate the correct icon
> Add dialog to view dependencies in GUI

- src/asammdf/blocks/mdf_v4.py
- test/test_mdf4.py
> Reading byte offset instead of bit count for channels

- src/asammdf/gui/dialogs/advanced_search.py
- src/asammdf/gui/widgets/batch.py
Fixes #880 
...but batch `.mat` export still does not work.
> Fix AttributeError: 'WindowsPath' object has no attribute 'configure'

- .pre-commit-config.yaml
- pyproject.toml
> Fix deprecation warnings with ruff 0.2.0

- src/asammdf/blocks/mdf_v4.py
- src/asammdf/blocks/v4_blocks.py
- src/asammdf/version.py
Extend `def _read_channels` to read nested CN blocks from within CA composition.
> Parsing of nested CA structures

- test/asammdf/gui/widgets/plot/test_PlotWidget_ContextMenu.py
- test/asammdf/gui/widgets/plot/test_PlotWidget_DoubleClick.py
Fix the CI by skipping tests that fails on Windows until these tests are fixed. This PR and PR #1101 fix the CI completely
> fix(ci): skip GUI tests that fails on Windows until fixed

- .pre-commit-config.yaml
- ISSUE_TEMPLATE.md
- benchmarks/bench.py
- src/asammdf/blocks/mdf_v3.py
- src/asammdf/blocks/mdf_v4.py
- src/asammdf/blocks/utils.py
- src/asammdf/blocks/v2_v3_blocks.py
- src/asammdf/blocks/v4_blocks.py
- src/asammdf/gui/widgets/formated_axis.py
- src/asammdf/gui/widgets/gps.py
- src/asammdf/gui/widgets/plot.py
- src/asammdf/gui/widgets/tabular.py
- src/asammdf/gui/widgets/tabular_base.py
- src/asammdf/signal.py
This PR puts imports together to avoid unnecessary git diffs in future PR and updates pre-commit hooks (ruff). There is no logic/functional changes in this PR
> Put imports together to avoid unnecessary git diffs in future PR

- .pre-commit-config.yaml
- pyproject.toml
- requirements.txt
- run_black_and_ruff.bat
- src/asammdf/__init__.py
- src/asammdf/blocks/mdf_v2.py
- src/asammdf/blocks/mdf_v3.py
- src/asammdf/blocks/v2_v3_blocks.py
- src/asammdf/blocks/v2_v3_constants.py
- src/asammdf/blocks/v4_constants.py
- src/asammdf/gui/widgets/tree.py
- src/asammdf/mdf.py
- src/asammdf/signal.py
- src/asammdf/tool.py
- src/asammdf/version.py
- test/test_cantp.py
- test/test_endianess.py
- tox.ini
> style: upgrade black to version 25

- pyproject.toml
> fix(ci): black fails because the regex in force-exclude is wrong

- .pre-commit-config.yaml
- requirements.txt
- run_black_and_ruff.bat
- tox.ini
> chore: upgrade Ruff to version 0.9

- test/asammdf/gui/widgets/Shortcuts/test_PlotWidget_Shortcuts.py
- test/asammdf/gui/widgets/plot/test_PlotWidget_PushButtons.py
I am not qualified to fix the GUI tests but I could at least fix the import errors
> Fix import errors in integration tests

- .github/workflows/wheels.yml
- pyproject.toml
> Include libdeflate in source distribution
