- asammdf/mdf4.py
> fix(mdf4): local variable 'vals' referenced before assignment

- asammdf/mdf_v3.py
- asammdf/mdf_v4.py
- asammdf/utils.py
The MDF3.get method was in master was masking irrelevant bits from
non-byte-sized integers and then relying on numpy.ndarray.astype to convert
back to signed. Since numpy only has byte-sized data types, this
meant that the wrong two's complement was used (e.g. 2**16 rather than
2**14 for a 14-bit integer encoded in a np.uint16).
This change computes two's complement for non-byte-sized signed integers
using numpy.where.
> Use numpy.where for signed non-byte-sized integers

- asammdf/mdf_v3.py
- asammdf/mdf_v4.py
Use utils.as_non_byte_sized_signed_int() for signed integer types
in _get_non_byte_aligned_data() as well.
> Correct two's complement for non-byte-aligned data

- asammdf/mdf_v3.py
mdf_v3 save_with_metadata lost header block's comment address.
> fix MDF.save comment address missing

- README.md
- Fixed link to CONTRIBUTING.md
- Stripped trailing white space.
- Removed preceding white-space in the example usage so that the code can be copy and pasted without an extra indent.
> Minor README.md fixes.

- documentation/benchmarks.rst
- documentation/buslogging.rst
- documentation/gui.rst
- documentation/intro.rst
- documentation/tips.rst
Hi Daniel,
I finally found the time to read through the whole documentation and while doing this, I made some small changes. Most of them are just correcting typos. Some others are fixing `REst` format (e.g. for links).
> improve documentation, mostly fixing typos

- asammdf/blocks/mdf_v4.py
If we do not reread dtype_format we get format information saved in channel previously which is based on aligned data (e.g. the  current code did not work because `byte_offset=11`, `bit_offset=7`, `bit_count=2`, the channel assumed `dtype_fmt = ">u2"` instead of `dtype_fmt = ">u2"`).
> Bugfix: Re-read dtype format information for unaligned data.

- asammdf/gui/widgets/plot.py
Pressing modifier keys [ctrl, alt] with the plot window open was causing the
following error to appear as a pop-up:
```
no access to protected functions or signals for objects not created from Python
File "/home/njames/repos/asammdf/asammdf/gui/widgets/plot.py", line 499, in keyPressEvent self.parent().keyPressEvent(event)
```
The Qt documentation [suggests](https://doc.qt.io/qt-5/qevent.html#ignore) calling QEvent::ignore() on unhandled keyPressEvents to pass them on to parent widgets.
> cease explicit propagation of unhandled key combinations to parents

- asammdf/blocks/mdf_v4.py
When generating signals for a structure, the designated size in bytes of
an element is continuously accumulated to calculate the offsets of
all elements. When an element does not have a size that is a multiple
of 8 (e.g., a boolean flag), the byte size was calculated to be zero,
which means that the subsequent channel erroneously received the same
offset. Fix by rounding up the byte size.
> fix offsets in mdf4 structures with non-byte members

- asammdf/blocks/utils.py
> Filesystem Spec is a project to unify various projects and classes to work with remote filesystems and file-system-like abstractions using a standard pythonic interface.
Some Anaconda articles on ```fsspec```:
- [Accessing Remote Data with a Generalized File System](https://www.anaconda.com/accessing-remote-data-generalized-file-system/)
- [Introducing Remote Content Caching with FSSpec ](https://www.anaconda.com/fsspec-remote-caching/)
Passing the object in to ```MDF()``` "is_file_like" returns True.
However the regex to find the start fails, they need to be read() as shown here:
https://github.com/SimulinkDevOps/Jupyter_MDF_Analysis/blob/4acf05b70e2bd6688113445261e8e77601666cae/22_S3_direct_loading.ipynb
With this fix you can load S3 files directly (and all other PyFilesystem objects) …
> Added workaround for FSSpec objects. Allows direct S3, Azure Datalake, etc loading.

- asammdf/signal.py
This PR fixes the following error:
```
UnboundLocalError: local variable 'encoding' referenced before assignment
```
> Fix UnboundLocalError

- asammdf/blocks/conversion_utils.py
The [mf4 generator example](https://asammdf.readthedocs.io/en/latest/examples.html#mf4-demo-file-generator) is broken, a KeyError exception is raised.
> Fix KeyError exception on conversion dict

- asammdf/blocks/mdf_v4.py
add raw argument to "get_can_signal" funktion, in mdf_v4.py file, default value is False
> add raw argument to mdf_v4.py

- asammdf/blocks/v4_blocks.py
While trying to merge multiple MF4 files together using the 'stack' function, the following error was thrown
```
INFO:__main__:MF4 stacking
Traceback (most recent call last):
File "C:\Users\james\.conda\envs\asammdf-env\lib\site-packages\asammdf\blocks\v4_blocks.py", line 140, in __init__
self.address = address = kwargs["address"]
KeyError: 'address'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "C:/tools/mdf_merger.py", line 82, in <module>
mdf = MDF.stack(path, sync=False)
File "C:\Users\james\.conda\envs\asammdf-env\lib\site-packages\asammdf\mdf.py", line 1917, in stack
signals, source_info, common_timebase=True
File "C:\Users\james\.conda\envs\asammdf-env\lib\site-packages\asammdf\blocks\mdf_v4.py", line 2721, in append …
```
> Fix 'str' object has no attribute 'write_bytes'

- asammdf/blocks/utils.py
The current get_text_v4 implementation strips '\0' (and whitespace) from the retrieved data block, but does not terminate the string at the first '\0' if it contains printable text after.
I ran into this when MDF.get() could not find some signals. Turns out their names were stored as b"Original_Name\0\0\0Other_Junk". The other junk was left there by a signal renaming utility.
> terminate text strings at \0

- asammdf/blocks/v4_blocks.py
When creating an attachment to save to disk, if attachment is not embedded and the provided bytes string is empty, then don't create an empty file.
I have a use-case where a video file attachment is saved along-side the MF4 on disk (i.e. not embedded). I'm processing the MF4 with asammdf, and want to keep the video file attachment in the new resultant MF4 I generate. If I copy the attachment over into the new MF4, it creates an empty file in the current working directory, which to me is unintended behaviour.
> Don't Write Empty Attachments

- asammdf/gui/widgets/plot.py
Fixes error when clicking or right-clicking the plot: `<class 'AttributeError'>: module 'PyQt5.QtGui' has no attribute 'QApplication'`
All other instances of QApplication in the code use `QWidgets.QApplication`
> Fix AttributeError when clicking plot

- asammdf/gui/widgets/tree.py
TreeWidget was using `mouseMoveEvent` to detect a drag, which meant if you moved your mouse even one pixel while clicking an item, you'd start a drag instead (I kept accidentally doing this). I replaced this with `startDrag`, which has a threshold before starting a drag.
> Fix drag behavior of TreeWidget

- asammdf/gui/utils.py
This makes sure the application continues to process events while a progress bar is showing. Otherwise it can appear to freeze or not update progress.
> Prevent freezing during long tasks

- asammdf/mdf.py
Fixes `interpolation_mode` in the `to_dataframe` call. Previously float interpolation always used the default mode 1.
closes #596
> [MDF] Use float_interpolation_mode in to_dataframe call

- asammdf/mdf.py
I splitted whereis and search in 2 functions as they are distinct features. They can still be used in combination:
```python
mdf = MDF()
channels = mdf.search("vehicleSpeed")
occurrences = [
(None, gp_idx, cn_idx)
for name in channels
for gp_idx, cn_idx in mdf.whereis(name)
]
signals = mdf.select(occurrences)
...
```
> refactor(mdf): split whereis and search as they are distinct features

- asammdf/blocks/mdf_v4.py
Encountered when reading empty files which do not end correctly, the program tried to read beyond file limits.
I encountered it with trying to read a channel. 
Although it is a case of an erroneous mf4 file, still such thing shouldn't happen.
> Stops reading from out side of file bounds.

- asammdf/mdf.py
Characters which are illegal (in Windows) for file names can be present in channel comments, escape characters could also be used in comments. 
When exporting to CSV without "single time base" the channel specific csv name contains the comment.
List of illegal characters on Windows: 
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file
> Added characters in file name to be replaced

- asammdf/gui/widgets/plot.py
Issue #640 
Do not add comments if user pressed cancel in the add window comment.
> Do not add comment if pressed Cancel

- asammdf/blocks/v4_blocks.py
Fix a bug that accidently overwrites hd comments common properties e tags with wrong informations
-> project and subject becoming author if they get passed in an own xml structure
.
> Fix a bug that accidently overwrites hd comments common properties

- asammdf/mdf.py
When iterating over an MDF file, a channel object is returned.
By default this is a converted channel. So the iteration takes a long time because every channel is converted.
Moreover, there is no possibility to convert a channel back to raw, only from raw to converted.
So I thought adding the option to iterate over channels without converting them would be nice and faster.
The default behavior remains the same, although after looking at the performance difference, I would say that perhaps the default behavior should be iterating raw signals.
The results of the tests I've made: 
```
Iteration speed test over file of size: 103.8 MB
Regular time to iterate over file: 1.91225 seconds
Raw time to iterate over file: 0.37859 seconds
Raw + physical convert time to iterate over file: 1.899 seconds …
```
> Allow iteration over mdf file object to return raw signals

- asammdf/mdf.py
HDF5 export was missing timestamps for the master channel(s) if single_time_base equals False.
> hdf5 export: Adding timestamps values to each group

- asammdf/gui/widgets/plot.py
With the latest changes the name and unit fields width when plotting was very large and took too much space from the plot.
This proposed change makes the field widths change depending on the channel name and unit length.
Ideally it would be possible to either remove some buttons to make the plot area even larger, have it as an option to exclude some of the buttons (such as font increase/decrease) or move them to a second line / buttom of the area. But that should be discussed.
> Dynamically set the width of the channel list in plot

- asammdf/mdf.py
Calling the convert function with "<...>" inside the message parameter let to an invalid XML Error in the Vector MDF Validator inside the File History Meta Data Block
> convert(): removed sharp clips in string parameter

- asammdf/blocks/mdf_v4.py
Added progress information while sorting all the groups.
- Added 102 extra steps in the load progress, 100 for sorting and 2 after sorting is completed.
- When incrementing the progress updates during sorting we first compute a step, based on the total number of steps we have (100), the number of groups and the total items and then we increment each sorting by the step count.
- If the previous step count (integer) is greater than the current step (integer) then we can update the progress. This avoids calling the callback function with floating values and avoids calling the callback function with the same current value of the progress bar - i.e. we only call when there's an update in progress.
> Fix for issue #741.

- asammdf/blocks/v4_blocks.py
Alternatively I see that another method is used further up in the codebase, starting on line 3400:
```
all_bytes = True
for v in ret.tolist():
if not isinstance(v, bytes):
all_bytes = False
break
if not all_bytes:
try:
ret = ret.astype("f8")
except:
if not as_object:
ret = np.array(
[np.nan if isinstance(v, bytes) else v for v in ret]
)
else:
ret = ret.astype(bytes)
```
We could use this check to see if we need to convert to `float` or `bytes`, but I wouldn't iterate over all items if we can help it.
> Fix for issue #770. Try to convert to float first, and if that fails convert to bytes

- src/asammdf/blocks/conversion_utils.py
method: conversion_transfer()
it seems that in some cases the argument 'conversion' is an empty dictionary.
an empty dict need to be handled the same way as None (which was already handled).
> bugfix: do not throw a AttributeError in case of an empty dict (conversion)

- src/asammdf/blocks/v4_blocks.py
Hi Daniel,
This is a small bug fix we realized when we could not extract the comment from the mdf file.
There seems to be an issue with the double and single quotes specified in the replace string.
The comment(variable) string seems to have single quotes in some of our mf4 files -` xmlns='http://www.asam.net/mdf/v4'`. 
Hence I have provided a fix which will take care of both the cases (double & single quotes)
It is also tested on different mf4 files with my colleague Monica K. @kmonica92 
Is this solution good enough if it works for you as well.
> Used regular expression

- src/asammdf/gui/utils.py
When modifying/extracting bus with the GUI, at the end of the process, there is an exception where the self.process QtSignal is missing a parameter.
This is because this signal is connected to a function expecting (self) parameter but none is given
The solution is to pass self.parent to it.
> QtSignal.emit() missing parameter

- .github/workflows/build.yml
- .github/workflows/coveralls.yml
- .github/workflows/main.yml
- .github/workflows/wheels.yml
- requirements_exe_build.txt
- src/asammdf/blocks/utils.py
- src/asammdf/gui/widgets/file.py
- src/asammdf/gui/widgets/plot.py
- src/asammdf/gui/widgets/tree.py
- test/asammdf/gui/__init__.py
- test/asammdf/gui/test_base.py
- test/asammdf/gui/widgets/test_FileWidget.py
- test/requirements.txt
- tox.ini
- `.coveragerc`
- adapted to consider py files from gui folder excepting `ui` folder.
- `coveralls.yml`
- few more libraries needs to be installed on Linux machine in order to get Qt running.
- display environment needs to be created because job is running in Linux terminal session.
- `main.yml`
- few more libraries needs to be installed on Linux machine in order to get Qt running.
- display environment needs to be created because job is running in Linux terminal session.
- additional steps are running considering matrix.os value
- `wheels.yml`
- `cibuildwheel` seems to execute the tests by-default, so command was adapted in order to avoid gui tests.
- pyproject.toml`
- style checks are executed but there differences between `py38` and `>py38`. Freeze to `py38` style.
- …
> [WIP] Add unit tests for GUI Widgets.

- src/asammdf/mdf.py
Hotfix for issue #859. 
No downcast is required if the sig.samples array is empty (e.g. because all signals are invalid).
> Only downcast signals if the samples array is not empty

- requirements_exe_build.txt
- src/asammdf/gui/widgets/tree.py
- src/asammdf/version.py
- test/asammdf/gui/widgets/test_PlotWidget.py
Package `QtPy` (dependency of `pyqtlet`) was freezed to `2.3.1`.
It seems that with newer one (`2.4.0`), pyinstaller cannot build binary:
```python
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.10.12/x64/bin/pyinstaller", line 8, in <module>
sys.exit(run())
File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/PyInstaller/__main__.py", line [124](https://github.com/danielhrisca/asammdf/actions/runs/6047454325/job/16410940716?pr=901#step:5:125), in run
run_build(pyi_config, spec_file, **vars(args))
File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/PyInstaller/__main__.py", line 58, in run_build
PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
File …
```
> Fix Group Activation from ContextMenu

- src/asammdf/gui/widgets/plot.py
- src/asammdf/gui/widgets/tree.py
- src/asammdf/version.py
- Update sub-groups icon when parent group state is changed
- Update channels color from groups
- Preserve sub-groups state
> Improve groups enable/disable handling.

- src/asammdf/blocks/v4_blocks.py
Hello,
I do not know why you decided to convert everything in the header comment to the tree structure. But I would like to add this simple support for the elist so it is not lost in the header.
Previously elist was working in version 7.0.7
> Add support for elist in mf4 header comment

- src/asammdf/mdf.py
Bugfix:
mdf iter_to_dataframe takes channels parameter to allow filtering.
In this case a filtering is set for the mdf and same member function is invoked.
However at the end of this `if` clause there is no return, effectively continuing into the "else" codepath instead of stopping the iteration. Effectively we get duplicated / more rows.
Added return.
fyi: @danielhrisca
> Add return to iter_to_dataframe when filtering channels

- src/asammdf/signal.py
- test/asammdf/gui/dialogs/test_FunctionsManagerDialog.py
- test/test_mdf.py
- test/utils.py
This print statement seems unnecessary. It originates from 4e2b2d27af1ed1312fdb4276bf4a80a9fa8e546e but I cant't see the purpose. Could it just be removed?
For me it started to appear just now that I changed my Python environment. Everytime I run Signal.plot I get an error printed (no actual error, just the traceback printed) because the call to gui.plot 4 lines above the print raises an Exception since importing PySide6 fails in my environment. But Signal.plot produces a plot, so no need to show an error I guess.
> unnecessary print statement removed

- .pre-commit-config.yaml
- pyproject.toml
- src/asammdf/blocks/mdf_v3.py
- src/asammdf/blocks/mdf_v4.py
- src/asammdf/blocks/utils.py
- src/asammdf/blocks/v2_v3_blocks.py
- src/asammdf/gui/dialogs/advanced_search.py
- src/asammdf/gui/dialogs/bus_database_manager.py
- src/asammdf/gui/dialogs/messagebox.py
- src/asammdf/gui/utils.py
- src/asammdf/gui/widgets/file.py
- src/asammdf/gui/widgets/plot.py
- src/asammdf/gui/widgets/tabular_base.py
- src/asammdf/mdf.py
- src/asammdf/tool.py
Can you check these?
```text
style: commands[1]> ruff check ./src
src/asammdf/gui/widgets/plot.py:136:8: PLR0124 Name compared with itself, consider replacing `b != b`
src/asammdf/gui/widgets/plot.py:144:8: PLR0124 Name compared with itself, consider replacing `b != b`
src/asammdf/gui/widgets/plot.py:4460:28: PLR0124 Name compared with itself, consider replacing `min_ != min_`
src/asammdf/gui/widgets/plot.py:4462:28: PLR0124 Name compared with itself, consider replacing `max_ != max_`
src/asammdf/gui/widgets/plot.py:4503:28: PLR0124 Name compared with itself, consider replacing `min_ != min_`
src/asammdf/gui/widgets/plot.py:4505:28: PLR0124 Name compared with itself, consider replacing `max_ != max_`
src/asammdf/gui/widgets/tabular_base.py:1382:16: PLR0124 Name compared with itself, …
```
> Activate Pylint Rules

- src/asammdf/mdf.py
- test/almost-J1939.dbc
- test/test_CAN_bus_loogging.py
I had a DBC file containing one message with non-extended ID.
asammdf refused to accept that and threw an exception even if the rest of the file was OK.
I think warning in this case may be a less drastic approach - the suggested change allows me
to run without modifying either asammdf locally _or_ my incoming data, while still passing the tests.
Speaking of tests - it seems to me that running the GUI tests on a large screen (3840 x 2160)
places the gui window in the lower right part of the screen, but it seems the cursor is placed farther 
and farther to "north-west", ie up and left - and after a while leaving the window which stops the
test sequence. Manually moving it back makes tests continue, but the behaviour is repeated,
Running on a "standard" sized screen does not seem to behave …
> Warn and relax global j1939 if non-extended IDs present

- src/asammdf/mdf.py
The channel group acquisition properties of a filtered MDF aren't copied across for MDF versions 4.20 and greater. See the example below for a minimal reproducible example:
```py
from asammdf import MDF, Signal
t, v = [0, 1], [2, 4]
acq_name = "ExampleTask"
signal_name = f"Task.Struct.Value"
for version in ("4.10", "4.20"):
mdf1 = MDF(version=version)
mdf1.append([Signal(v, t, name=signal_name)], acq_name=acq_name)
mdf2 = mdf1.filter([signal_name])
cg_nr, _ = mdf2.channels_db[signal_name][0]
result_acq_name = mdf2.groups[cg_nr].channel_group.acq_name
print(f"Version {version}: {result_acq_name}")
```
I would expect this to print
```
Version 4.10: ExampleTask
Version 4.20: ExampleTask
```
However instead we see
```
Version 4.10: ExampleTask
Version 4.20: None
```
This appears to be due to …
> Provide acq_name and acq_source to append method when filtering

- src/asammdf/blocks/mdf_v4.py
Use the `temporary_folder` value when copying the MDF4 file to a temporary location and use `gettempdir()` as fallback.
> Use temporary folder in MDF4

- test/test_CAN_bus_loogging.py
Retrieving zips with urlllib requires explicit import of its request module
> Add import for retrieving zips

- src/asammdf/blocks/v2_v3_constants.py
fix tz_offset being unsigned int, however it's supposed to be a signed int
In the MDF spec for v3:
INT16 1 UTC time offset in hours (= GMT time zone)
The time offset is defined as INT16, not UINT16.
If the time offset is negative, but interpreted as UINT16, it will result in a very large positive number.
> fix tz_offset being unsigned int

- .gitignore
- asammdf.spec
- src/asammdf/gui/dialogs/dependencies_dlg.py
I had to change a few things, so pyinstaller builds can access the package metadata.
Here is the new button below the table:
The output might be useful for creating bug reports:
<details>
<summary>Example Output</summary>
```
Package            Version
--------------------------
PySide6            6.8.1
PySide6-Addons     6.8.1
PySide6-Essentials 6.8.1
QtPy               2.4.2
asammdf            8.1.0.dev3
attrs              24.2.0
backports.tarfile  1.2.0
canmatrix          1.0
cffi               1.17.1
chardet            5.2.0
click              8.1.7
colorama           0.4.6
cramjam            2.9.0
cryptography       44.0.0
faust-cchardet     2.1.19
future             1.0.0
h5py               3.12.1
hdf5storage        0.1.19
importlib-metadata 8.0.0
isal               1.7.1 …
```
> Add button to create a report of installed dependencies

- .readthedocs.yml
The last successful documentation build is for version 7.3.*
Lately the build fails with
> Fix readthedocs "Config file validation error"

- CONTRIBUTING.md
Slightly more detailed instructions. I myself was stuck for a while because I hadn't cloned the submodule `ext/libdeflate`. I also think it's not obvious that a C compiler is required to build this package.
The lines for setting up a virtual environment and install in editable mode are really useful, but the activation command is different in Windows so I tried to clarify that.
> doc: clarified developer instructions

- test/asammdf/gui/widgets/batch/test_BatchWidget_Tab_ModifyAndExport.py
These 2 tests keep failing in CI (see #1142 #1139 #1138 #1137). Something is wrong but I lack the time to fix it so I am suggesting to skip them until they are fixed. Maybe @FillBk you want to have a look into this since you added a lot of tests for the GUI recently?
Ready for merge
> fix(ci): skip test_resample_by_step_0 and test_resample_by_step_1 until fixed

- pyproject.toml
- requirements.txt
- test/requirements.txt
- tox.ini
Switching to using hyphens instead of underscores fixes the issue. Underscores are replaced with hyphens anyway when packaging asammdf because the standard from pypa does not accept underscore: https://packaging.python.org/en/latest/specifications/core-metadata/#core-metadata-provides-extra
For pip install, it will still continue to work for users using underscores because pip replaces the underscores with hyphens automatically.
Ready for merge
> fix: tox does not install extras if they have underscores in their name

- src/asammdf/blocks/v4_blocks.py
The code for the ChannelConversion block works well but one of its comments has a small typo contradicting the standard.
The docs are autogenerated from the code so they also show this typo.
> Corrected misleading typo in ChannelConversion block's comment

- CONTRIBUTING.md
- src/asammdf/blocks/mdf_common.py
- src/asammdf/blocks/mdf_v3.py
- src/asammdf/blocks/mdf_v4.py
- src/asammdf/blocks/source_utils.py
- src/asammdf/blocks/v2_v3_blocks.py
- src/asammdf/blocks/v4_blocks.py
- src/asammdf/mdf.py
- src/asammdf/signal.py
This PR contains only docstring changes, except a minor fix in CONTRIBUTING.md. The changes are mostly stylistic, for example capitalization, punctuation, italicization, fixing typos and indentation. I think this package deserves proper-looking docstrings :)
Some code examples have been fixed, many relating to `MdfException: Multiple occurrences ...`. There are also a few minor corrections, most notably a missing "not" in the decription of the `include_ends` argument.
I have not gone through all files but rather focused on the MDF and Signal objects and their methods, whose docstrings I assume are the ones most frequently read.
> Docstring style, examples, corrections

- pyproject.toml
Fixes #1158 
https://typing-extensions.readthedocs.io/en/latest/index.html#typing_extensions.TypeIs
> fix: TypeIs requires typing-extensions 4.10

- pyproject.toml
- src/asammdf/blocks/mdf_v4.py
- src/asammdf/blocks/utils.py
- src/asammdf/gui/dialogs/error_dialog.py
- src/asammdf/gui/dialogs/messagebox.py
- src/asammdf/gui/widgets/can_bus_trace.py
- src/asammdf/gui/widgets/flexray_bus_trace.py
- src/asammdf/gui/widgets/formated_axis.py
- src/asammdf/gui/widgets/lin_bus_trace.py
- src/asammdf/types.py
- test/asammdf/gui/resources/functions.py
The rules fixed in 82e60e7c1307969add2c78326d4b9a8faccf8561 were stabilized in ruff 0.10, previously only preview. UP007 error fixed in fe2391c283dd03a7d606a4b8ca83b56ebec8875e is due to target-version changed to py310.
I haven't raised the ruff version here but will do so in #1151.
> Fix lint issues

- pyproject.toml
When updating older asammdf installations, the dependencies are not automatically updated to ensure numpy 2.0 compatibility.
`PySide6>=6.7.0` is not numpy related, but older versions fail with an AttributeError.
I also removed the `testing` extra, i does not seem to be used anywhere.
> Raise min. dependency versions for numpy2

- src/asammdf/signal.py
This was partially fixed in #830 but two places were missed.
> Fix 'FigureCanvasTkAgg' object has no attribute 'set_window_title'

- src/asammdf/blocks/mdf_v4.py
compressed_size is used instead of original_size when calling decompress function
> fix(mdf_v4): wrong size when decompressing DZ block

- .github/workflows/build.yml
The arm build currently fails because of https://github.com/mcfletch/pyopengl/pull/146.
Set fail-fast: false so the other OS versions can be completed.
> Set fail-fast: false in build.yml

- pyproject.toml
- src/asammdf/blocks/mdf_v4.py
- src/asammdf/blocks/v4_blocks.py
NumPy improved its type annotations in release 2.3.0, resulting in two new errors fixed in this PR. Note that the mypy plugin has been deprecated
> fix: mypy errors introduced by numpy 2.3.0

- src/asammdf/version.py
- test/asammdf/gui/widgets/batch/test_BatchWidget_Tab_BusLogging.py
- test/asammdf/gui/widgets/batch/test_BatchWidget_Tab_ModifyAndExport.py
- test/test_CAN_bus_logging.py
- test/test_mdf.py
This is an adapted version of Sebastien Noël's patch:
https://salsa.debian.org/python-team/packages/asammdf/-/blob/master/debian/patches/skip-tests-internet.patch?ref_type=heads
The current behaviour is retained by default
> allow to skip tests requiring internet access by defining NO_NET_ACCESS

- src/asammdf/blocks/mdf_v3.py
**Issue**
I use the channel.display_names attribute to control channel naming for pandas dataframe output. mdf.to_dataframe(..., use_display_names=True, ...) This is useful for adding device names to channels in case of duplicate channel names from different devices.
With MDFv4.x *.mf4 files, this works fine by changing the display_names attribute in the Channel object and then calling the to_dataframe() method.
However, with MDFv3 *.dat files, the behaviour was different. Even after setting the display_names attribute, the expected display names were not present in the dataframe output. I found that the display_names attribute was cleared whenever the get_channel_metadata() method was re-run while with an MDFv4 file, this was not the case.
``` python
from asammdf import MDF
mdf = …
```
> Align channel metadata behaviour between v3 & v4 blocks

- src/asammdf/blocks/mdf_v4.py
After upgrading to INCA V7.2 I get .mf4-files that contain data of type signed intel. Adding those lines fixes the problem and I can import the measurement.
The following was the error log
```---------------------------------------------------------------------------
MdfException                              Traceback (most recent call last)
[c:\%some_path%](file:///C:/%some_path%) %some_file%.ipynb Zelle 3 line 5
[3](vscode-notebook-cell:/c%3A/%some_file%.ipynb#W2sZmlsZQ%3D%3D?line=2) dfs = []
[4](vscode-notebook-cell:/c%3A/%some_file%.ipynb#W2sZmlsZQ%3D%3D?line=3) for file in files:
----> [5](vscode-notebook-cell:/c%3A/%some_file%.ipynb#W2sZmlsZQ%3D%3D?line=4)     df = MDF(file).to_dataframe(raster=0.01)
[7](vscode-notebook-cell:/c%3A/%some_file%.ipynb#W2sZmlsZQ%3D%3D?line=6) …
```
> process signal_data with data_type v4c.DATA_TYPE_SIGNED_INTEL and v4c.DATA_TYPE_SIGNED_MOTOROLA
